# prevent automatic schema changes
spring.jpa.hibernate.ddl-auto=validate

# disable SQL logging in production
spring.jpa.show-sql=false

# logging
logging.level.root=WARN
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=WARN

# don't expose stack traces to clients
server.error.include-stacktrace=never
server.error.include-message=never
